name: nocab_logger
description: Logger for Nocab
version: 1.0.0
repository: https://github.com/nocab-transfer/nocab-logger

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  logging: ^1.1.1
  path: ^1.8.3
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
