name: nocab_logger
description: Logger for Nocab
version: 1.0.0
repository: https://github.com/nocab-transfer/nocab-logger

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.21.0
